// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUUIDProcessor is a mock of UUIDProcessor interface.
type MockUUIDProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDProcessorMockRecorder
}

// MockUUIDProcessorMockRecorder is the mock recorder for MockUUIDProcessor.
type MockUUIDProcessorMockRecorder struct {
	mock *MockUUIDProcessor
}

// NewMockUUIDProcessor creates a new mock instance.
func NewMockUUIDProcessor(ctrl *gomock.Controller) *MockUUIDProcessor {
	mock := &MockUUIDProcessor{ctrl: ctrl}
	mock.recorder = &MockUUIDProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDProcessor) EXPECT() *MockUUIDProcessorMockRecorder {
	return m.recorder
}

// generateUUID mocks base method.
func (m *MockUUIDProcessor) generateUUID() (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "generateUUID")
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// generateUUID indicates an expected call of generateUUID.
func (mr *MockUUIDProcessorMockRecorder) generateUUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "generateUUID", reflect.TypeOf((*MockUUIDProcessor)(nil).generateUUID))
}
